### ISSUE TITLE
Error while trying to run

### ISSUE THREAD

**Issue by Codeiology** [CommanderGL/UBTW#1]
I followed the directions on README.md perfectly. I forked it and made it into a repository, and then changed my working directory to nodeunblocker.com and tried to install dependencies for it, and got the error:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /workspaces/UBTW/nodeunblocker.com/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/workspaces/UBTW/nodeunblocker.com/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

I renamed package-lock.json to package.json hoping something would happen this time and it worked flawlessy. When I tried to run it with 'npm start', however, I got this:

npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2023-11-05T19_03_07_660Z-debug-0.log

Please fix.

**Comment by WalterAslanWhite** [comment]
Exact same thing happened to me

**Comment by Gitkickva** [comment]
me too

**Comment by wubblebubbleball** [comment]
same here

**Comment by Topher7lol** [comment]
me 5

**Comment by Topher7lol** [comment]
its probably old so some code is broken

**Comment by CommanderGL** [comment]
Sorry I made this when I was 10 and am working on a newer version please wait

**Comment by CommanderGL** [comment]
UBTW2 has been released!
https://github.com/CommanderGL/UBTW2
