### ISSUE TITLE
npm i

### ISSUE THREAD

**Issue by amongudyeah** [CommanderGL/UBTW#2]
i dont know much about coding but how do i run npm i

**Comment by Topher7lol** [comment]
you type npm i

**Comment by amongudyeah** [comment]
it said error and stuff

**Comment by amongudyeah** [comment]
![Screenshot 2024-02-29 9 54 50 AM](https://github.com/CommanderGL/UBTW/assets/161071623/90740744-2ff9-4bee-95cc-2ab6dec8a0da)
 like this

**Comment by Topher7lol** [comment]
you needs to cd nodeunblocker.com then cd Riptide then npm i, otherwise its broken, and maybe dont run it in a codespace

**Comment by CommanderGL** [comment]
Please stand by while I work on version 2

**Comment by CommanderGL** [comment]
UBTW2 has been released!
https://github.com/CommanderGL/UBTW2
