### ISSUE TITLE
Packages Missing (Errors when running `npm i`)

### ISSUE THREAD

**Issue by ANCJI** [CommanderGL/UBTW#4]
When running `npm i` in the VSCode terminal, many errors are displayed. This is because there is no "package.json" file inside of the "Riptide" and "nodeunblocker.com" folders. It cannot install the package because it has not been placed inside of the directories. Is there anywhere that the package file is supposed to be, or has it not been uploaded whatsoever?

**Comment by Topher7lol** [comment]
just in the workspace

**Comment by CommanderGL** [comment]
Version 2 in the works

**Comment by CommanderGL** [comment]
UBTW2 has been released!
https://github.com/CommanderGL/UBTW2
